# Generated by Django 4.1.4 on 2022-12-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tile',
            new_name='title',
        ),
    ]
